name: Build Release

on:
  push:
    branches:
      - "master"
      - "main"
    tags:
      - "**"
  pull_request:
    branches:
      - "master"
      - "main"
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0 && go generate ./...
      - name: Test
        run: go test ./...
  build-executable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: echo $GOPATH
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: dist
          prefix: etd
          v: true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: dist/*